config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root 'cargos#index'

  resources :cargos
  resources :users
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cargo.rb
# frozen_string_literal: true
class Cargo < ApplicationRecord
  include AASM

  validates :name,
            :surname,
            :middle_name,
            :phone,
            :email,
            :weight,
            :length,
            :width,
            :height,
            :origins,
            :destinations,
            presence: true
  validates :phone, format: { with: /(^\+?[(]?[0-9]{3}[)]?[-\s.]?[0-9]{3}[-\s.]?[0-9]{4,6}$)/ }
  belongs_to :user

  scope :org_by, ->(org_id, group_by = nil) {joins(:user).where(user: {organization_id: org_id}).group(group_by)}

  aasm column: :status do
    state :processing, initial: true
    state :delivering, :delivered

    event :cargo_processing do
      transitions from: :processing, to: :delivering
    end

    event :cargo_delivery do
      transitions from: :delivering, to: :delivered
    end   
  end
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :users
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cargos, dependent: :destroy
  belongs_to :organization, optional: true

  def is_operator?
    role == 'operator'
  end

  def is_organization_admin?
    role == 'orgadmin'
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit::Authorization

  rescue_from Pundit::NotAuthorizedError, with: :user_with_wrong_role

  private

  def user_with_wrong_role
    flash[:alert] = 'You have the wrong role to perform this action'
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/cargos_controller.rb
# frozen_string_literal: true

class CargosController < ApplicationController
  before_action :authenticate_user!

  def index
    if current_user.is_organization_admin?
      @cargos = Cargo.where(user_id: current_user.organization.users.ids).page(params[:page])
      @users = current_user.organization.users
    else
      @cargos = Cargo.where(user_id: current_user.id).page(params[:page])
    end

    @cargos = @cargos.rewhere(user_id: params[:operator_id_filter]) if params[:operator_id_filter].present?
    @cargos = @cargos.order("#{params[:sort]} #{params[:direction]}") if params[:sort].present?

    authorize @cargos
  end

  def show
    @cargo = Cargo.find(params[:id])
    authorize @cargo
  end

  def new
    @cargo = Cargo.new
    authorize @cargo
  end

  def create
    authorize Cargo
    outcome = Cargos::CreateCargo.run(params[:cargo].merge(user: current_user))
    if outcome.valid?
      redirect_to(outcome.result)
    else
      redirect_to new_cargo_path
    end
  end

  def edit
    @cargo = Cargo.find(params[:id])
    authorize @cargo
  end

  def update
    cargo = Cargo.find(params[:id])
    authorize cargo
    outcome = Cargos::UpdateCargo.run(params[:cargo].merge(cargo: cargo))
    if outcome.valid?
      redirect_to(outcome.result)
    else
      redirect_to edit_cargo_path
    end
  end

  def destroy
    cargo = Cargo.find(params[:id])
    Cargos::DestroyCargo.run(cargo: cargo) if current_user == cargo.user
    redirect_to(cargos_path)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    redirect_to cargos_path
  end

  def show
    @user = User.find(params[:id])
    authorize @user
    if current_user.is_organization_admin? && Cargo.org_by(current_user.organization.id).present?
      org_id = @user.organization.id
      @widgets = [
        Cargos::CountWidget.call(org_id),
        Cargos::CountWidget.call(org_id, :sorted),
        Cargos::PriceWidget.call(org_id),
        Cargos::PriceWidget.call(org_id, :average),
        Cargos::DistanceWidget.call(org_id),
        Cargos::DistanceWidget.call(org_id, :max)
      ]
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/cargos_helper.rb
# frozen_string_literal: true

module CargosHelper
  def sortable(column, title = nil)
    title ||= column
    direction = column == sort_column && sort_direction == 'asc' ? 'desc' : 'asc'
    link_to title, { sort: column, direction: direction }
  end
  
  def sort_column
    Cargo.column_names.include?(params[:sort]) ? params[:sort] : 'price'
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/cargos/_form.html.erb
<%= form_with model: cargo do |form|%>
  <div>
   <h3> <%= form.label :name%> </h3> 
    <%= form.text_field :name%>
 </div>

  <div> 
    <h3> <%= form.label :surname%> </h3>
    <%= form.text_field :surname%>
  </div>

  <div> 
    <h3> <%= form.label :middle_name%> </h3>
    <%= form.text_field :middle_name%>
  </div>

  <div> 
    <h3> <%= form.label :phone%> </h3>
    <%= form.telephone_field :phone%> 
  </div>

  <div> 
    <h3> <%= form.label :email%> </h3>
    <%= form.email_field :email%>
  </div>

  <div> 
    <h3> <%= form.label :weight%> </h3>
    <%= form.number_field :weight, step: :any%>
  </div>

  <div> 
    <h3> <%= form.label :length%> </h3>
    <%= form.number_field :length%>
  </div>

  <div>
    <h3> <%= form.label :width%> </h3>
    <%= form.number_field :width%>
  </div>

  <div> 
    <h3> <%= form.label :height%> </h3>
    <%= form.number_field :height%> 
  </div>

  <div> 
    <h3> <%= form.label :origins%> </h3>
    <%= form.text_field :origins%> 
  </div>

  <div> 
    <h3> <%= form.label :destinations%> </h3>
    <%= form.text_field :destinations%> 
  </div>

  <% if controller.action_name == "new"%>
    <h3>
      <%= form.submit "CREATE" %>
    </h3>
  <% else %>
    <h3>
      <%= form.submit "UPDATE" %>
    </h3>
  <%end%>
<%end%>

<div>
  <h2>
    <%= link_to "BACK", cargos_path %>
  </h2>
</div>

app/views/cargos/edit.html.erb
<h1><p>Edit cargo information</p></h1>

<%= render "form", cargo:@cargo %>

app/views/cargos/index.html.erb
<% if user_signed_in?%>
  <div>
    <%= button_to "SIGN OUT", destroy_user_session_path, method: :delete, data: { turbo: "false" } %>
  </div>
<%end%>

<% if current_user.is_organization_admin? %>
  <div>
    <h3>
      <%= link_to "Personal Area", current_user%>
    </h3>
  </div>
<%end%>

<h1>ORDERS</h1>

<strong>
  <tr>
    <th> <%= sortable "price", "Sorted by price" %> </th>
    <th> <%= sortable "distance", "Sorted by distance" %> </th>
    <th> <%= sortable "created_at", "Sorted by create date" %> </th>
  </tr>
</strong>

<% if current_user.is_organization_admin? %>
  <%= form_for(cargos_path, method: 'get') do %>
    <%= select_tag('operator_id_filter', options_from_collection_for_select(@users, :id, :email))%>   
    <%= submit_tag("Search")%>
  <%end%>
<%end%>

<% @cargos.each do |cargo|%>
  <div>
    <h2>
      <%= link_to "Order № #{cargo.id} #{cargo.origins} - #{cargo.destinations}", cargo %>
    </h2>
  </div>
<%end%>

<%= paginate @cargos %>

<%if current_user.organization.present?%>
  <div>
    <h4>
      <%= link_to "CREATE ORDER", new_cargo_path %>
    </h4>
  </div>
<%else%>
  <h4> <strong> You don't have a role to create cargos yet </strong> </h4>
<%end%>

app/views/cargos/new.html.erb
<h1><p>Enter cargo information</p></h1>

<%= render "form", cargo:@cargo %>

app/views/cargos/show.html.erb
<h1>INFORMATION ABOUT <%= @cargo.id %> ORDER</h1>
<h2>
  <div>
    <%= @cargo.name %>
  </div>
  <div>
    <%= @cargo.surname %>
  </div>
  <div>
    <%= @cargo.middle_name%>
  </div>
  <div>
    <%= @cargo.phone %>
  </div>
  <div>
    <%= @cargo.email %>
  </div>
  <div>
    <%= @cargo.weight %>
  </div>
  <div>
    <%= @cargo.length %>
  </div>
  <div>
    <%= @cargo.width %>
  </div>
  <div>
    <%= @cargo.height %>
  </div>
  <div>
    <%= @cargo.origins %>
  </div>
  <div>
    <%= @cargo.destinations %> 
  </div>
  <div>
    <%= @cargo.distance %>
  </div>
  <div>
    <%= @cargo.price %> "RUB"
  </div>
</h2>

<h2>
  <%= link_to "Update cargo", edit_cargo_path %>
  <%= button_to "Delete cargo", cargo_path(@cargo), method: :delete %>
</h2>

<h2>
  <%= link_to "See previous applications", cargos_path%>
</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Delivery</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/users/show.html.erb
<% if current_user.is_organization_admin?%>
  <h2>
    <strong>
      Hello <%=current_user.email%>  
    </strong>
  </h2>

  <h3> На сегодняшний день: </h3>
    <% @widgets.each do |widget| %>
      <div><h3><strong>
        <%= widget[:text] %>
        <%= widget[:data] %>
      </div></h3></strong>
    <%end%>
  <h2>
    <%= link_to "BACK", cargos_path%>
  </h2>
<%end%>